# simplifed version of the upstream travis configuration

language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: true
env:
    global:
    - TESSERA_JAR="$HOME/tessera.jar"
    - TERRAFORM_CMD="/usr/local/bin/terraform"
    - QUORUM_CLOUD_TEMPLATES_DIR=quorum-cloud/aws/templates
    - QUORUM_SOCKSPROXY_HOST=localhost
    - QUORUM_SOCKSPROXY_PORT=5000
    # Terraform Variables
    - TF_VAR_region=us-east-1
    - TF_VAR_is_igw_subnets=false
    - TF_VAR_subnet_ids="[\"subnet-4c30c605\",\"subnet-4c30c605\",\"subnet-09263334\",\"subnet-5236300a\"]"
    - TF_VAR_bastion_public_subnet_id="subnet-3a8d8707"
    - TF_VAR_access_bastion_cidr_blocks="[$(dig +short nat.travisci.net | sed -e 's/$/\/32\"/g' | sed -e 's/^/\"/g' | paste -s -d, -)]"
    # - TF_VAR_access_bastion_cidr_blocks="[\"$(curl -s ipecho.net/plain)/32\"]"
    # AWS Configuration
    - secure: "N0zq0g0OUCYFJ7L3Kxibv7+lqEACfuBqMBVicpG3Thq/RtL7J/+LlGjYiDtMrHZyCG9vQVDnug6iSh9v6mixelDYaOXLiz2DqiYkc5r7rB3Z8J+eS2CzG+jcYs6tgmP6CtvlWjvldFf5F/w9T36RHP/WfF5DjcKqk9gF8KeHR7j9SAD91wUcp5ZWzoeASSk3mvaaVoGeTvgMtr+HbgEiAaCNwxZn7P14eC5dFJ8Oyihem2bW2+DOxTaEOQeMxtTxh+0ve2IWEqt+y0F6qWMp7H93CuehsvMHbzNhG4Xb9HVMj6ik0xiktWYAVlIqBPfWPVTy3wHlSPrA1hMZTXJ8/JtNT4Xx14WiBqN1X14W26YionmMtWHKYpDCqBkwVcSjT/raeeIT4k7CR7lY0mTwm+oGSxLPHvbPetWGdMSq9X9YO8+rqGJoKUHnSsU7Z0cniFnnhZdPSqZjSeOCz3++sHbaUiXgSvWEWEM3kB24uFS3jspI8E6nzENwEYtMq7qz3dFVwZPGB7WAmAc6Dv8vgfVH4la5TLW8ko3qyycCPVqcBNQjMUQeCNCJyfujC3mBc5eZ8WI2Rm/fg14XPgdjRr02gYYx6k3WQYu/hXRYHC/LbkVfCixGTVS0NNoPGdX+O8gNwT44+7AhZS7477P+otvVrAYSTNfwpGcskbbWtWg="
    - secure: "VhDu25BY2jglaEYyFXDIDSrwtne1A98fGI4fgrBddyEfVo/qUKjYFsj/QPiN7rdmuvUQZuy4TYsC6rEnVfehesQQZ2PEvaMRVKU0LRm7uOlA0pV3VRggt8jClXGG9i3Nbe8UMhC9zZDbrY9vtErkI47Z8NHxy9O2mJMYmgoTmBgaFm4Gk4vUz5IXbMmoZmKLO36ODJqqAbwKVtWT8fbK8C7k/Gm2p8CoeNFYsFsR9AtJUP8vAcq9mOngPdTCRb9je3DQkdrF2nCMD9pHpEJXvnCZyQ/dFfGwlVRS++gh31ieCGmIhjWVtpIRTBZOaHAiPUXaAI/fvFYxkiW4TYA+hm58sIxCQ5XcOTq1DUIGGnNTbFSqvR3Y33PB3SwEG6cnE7PdBIXqRNvb2sarkWtUipWMwLRx0FeHkZv0UESorL+Ell4aQN/Kwn8VnnLNFyWiI1uCjZ1LriSmmldX2eCFHW0MNMNb2sSsrCufT56N62JlfvsoFipz0nugthJGPPWAvxCKL/oUAzlAq4iSPf6iJB/93Y/eTcaf7sS18iZcOCjrkLl7I/1DW/2NfVX1OJeZWgRgubweDwvcD00ofXDvG22ZxNLEcLRWIf9j6UlPJb+AL24XwKmD1fDu0aPpGjbJ5L+9DbMF0Lw1N9Zy8lWjTDMggdGKFJ+5agCgJgtqGVc="
    # Github Page configuration to publish test report
    - secure: "rO5mn5nK3LPjggc2Yid+VC0F37vCsQVUxKlOP4llVbv7JnoLuBp4uYq3swp0XF3i58GOoGdU6s/K28b1f8hYEHV0G67epSNObCKPBBahaAYoNiW/vB4kh1D/4GQ5aJwmhoT889IAf/Uy4EonDiTerOrsxM7V1l6X0cZOl2Opin0AB2AvZCnpVfppPftlS18Xm/q+tp4/UVXhF4u4BI7HqbDJmctWwpytIm+9tjT8pUDKTEOjAj/HgoG3p6CHZh5ucR8uZBEHu2a8wmPhxh8beuJPBLKslB/yqjws0+XzICHsvWoc43FbgB2e1BZlaNsAzbE3FLE7RxZ/sIigQewJf50ms+NA2rjD2LHvGj+bBlluvrxtGfZaN0Cb3xgh03NguKwsWUkCUiQrgt0rhCm0//PwXxDnF83m1DFMTre3JhQAUDa0DjvEaPwiOLLRuYyL6yTloMOV/q1tRnL3VzQxpc8qjChKA4mMtB7jNYJ5mCDEjBSFOdzeLEyq/oWoj4tKY+j36QC0VhvOWEkazBurufWnXCxC58KlmEJDXBzYGDuW5HsqeQvNUM5Ozd3ugpXSn/CckVdElX4z8brXmEVpGRuxZQd4djJ4tuXGXmcWwCKhtmL8khtOy9KXy3EmsM/oN0o7lYglTG9M8MKgUits9Yaiv01Fd4HCMS104dFL3LY="
    - REPO_NAME=jpmorganchase.github.io
    - REPO_OWNER=jpmorganchase
    - GITHUB_USERNAME=trung
cache:
  directories:
  - $HOME/.m2
before_install:
  - wget https://github.com/jpmorganchase/tessera/releases/download/tessera-0.6/tessera-app-0.6-app.jar --O tessera.jar -q
  - sudo cp tessera.jar $HOME
  - sudo chmod 755 $HOME/tessera.jar
  - wget https://github.com/getgauge/gauge/releases/download/v1.0.3/gauge-1.0.3-linux.x86_64.zip -O gauge.zip -q
  - sudo unzip -o gauge.zip -d /usr/local/bin
  - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip -O terraform.zip -q
  - sudo unzip terraform.zip -d /usr/local/bin
  - terraform version
  - git clone https://github.com/jpmorganchase/quorum-cloud.git $TRAVIS_BUILD_DIR/quorum-cloud
  - git clone https://github.com/amalrajmani/quorum-acceptance-tests.git $TRAVIS_BUILD_DIR/quorum-acceptance-tests
install:
  - cd $TRAVIS_BUILD_DIR/quorum-acceptance-tests
  - gauge telemetry off
  - gauge install

addons:
    apt:
        update: true
        sources:
        - sourceline: ppa:ethereum/ethereum
        - sourceline: ppa:openjdk-r/ppa
        packages:
        - openjdk-8-jdk
        - dpkg # fixes issue with dpkg-deb error due to travis image issue
        - openssh-client
        - dnsutils
        - maven
        - solc
        - jq
        - curl

matrix:
  include:
    - name: raft
      os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      env:
        - TF_VAR_consensus_mechanism=raft
        - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES
        - cd $TRAVIS_BUILD_DIR/quorum-acceptance-test
        - ./src/travis/7nodes/raft-init.sh
        - ./src/travis/7nodes/raft-start.sh tessera
        - set +e
        - ./src/travis/run_tests.sh
        - set +e
        - ./src/travis/7nodes/stop.sh
        - set +e
        - cd $TRAVIS_BUILD_DIR
        - go run build/ci.go test -coverage $TEST_PACKAGES

    - name: istanbul
      os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      env:
        - TF_VAR_consensus_mechanism=istanbul
        - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
      script:
          - sudo modprobe fuse
          - sudo chmod 666 /dev/fuse
          - sudo chown root:$USER /etc/fuse.conf
          - go run build/ci.go install
          - go run build/ci.go test -coverage $TEST_PACKAGES

    - os: osx
      osx_image: xcode9.2 # so we don't have to deal with Kernel Extension Consent UI which is never possible in CI
      go: 1.9.x
      sudo: required
      script:
        - brew update
        - brew install caskroom/cask/brew-cask
        - brew cask install osxfuse
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES


notifications:
  slack:
      rooms:
      - secure: "C2sbBrFdBIL7kY2j/5pE19/e1QbfMJ58HcN2OhK6+RSGyv08W3UQsCSBPE3SNUmgYPkS5Oo46ikwm0N8CLtapOhc1rdIZV6ikxJQBs5gYUya8+8umlUMCZAV6fRRUxz1KXGMvwfvSmeivWm5oI4iEL6RkM8Sy2LTfLAzqxTCwyx18T4JTvgPyv8pQ+ZGsynQykkBaSFmLS6XQjmMlWOTuMdv7LsLofqn1ivSl7B+kR0eDJggUGGNm/B+JRySuroUo2Cwf9/DdpSCwfs76sEHuXcCeHKmCfkzUVAqve2XBGfsAdPXwvjoGo285e07FraIq2J+4oQSaNyWuExK/RQCNln5zZKNILObEUH7qF/oaJpBt82M0NreaPsczuB98eRvkoM9t5ki3rLk7GKSGL87QraZe1gxZ0TLe/cnb0OsHbhUKnW71WuTS/s+s9vUchCr/Dmer+Cr0sqbS4+cRD4yWAuYEfsAR50yAWymxg0pmRKlffCJpU1pmcEmcOLsnJEdvh8TZu/S9RFoZBPvzQxc+EbifMaY6AWPHT1NmFcXlGzHWrLmj2S/hhngr+rRiqE704pBk/odf7jV3H/P7sPXZPiK4y0+Pj0UvupDeAGUj/Et8Nt3+6VW3OzXgOIrpYCmxlS9GUleecz9JQ/dP513/R3v/GutYNU5P+XRhYMm4EQ="
      on_success: always
      on_failure: always
      on_pull_requests: false
      template:
      - "Build <%{build_url}|#%{build_number}> of %{repository_slug}@%{branch}"
      - "%{result} in %{duration}"
      - "<https://jpmorganchase.github.io/%{repository_name}/docs/html/|Test Specifications>"
      - "Execution reports: <https://jpmorganchase.github.io/%{repository_name}/raft/|Raft> - <https://jpmorganchase.github.io/%{repository_name}/istanbul/|Istanbul>"

