
# Project information
site_name: Quorum
site_url: https://docs.goquorum.com/
site_description: A permissioned implementation of Ethereum supporting data privacy
site_author: Quorum
copyright: Quorum 2019

# Repository
repo_name: quorum
repo_url: https://github.com/jpmorganchase/quorum

nav:
    - Home: index.md
    - Getting Started:
        - Quickstart: Getting Started/Getting Started Overview.md
        - Installing: Getting Started/Installing.md
        - Examples: Getting Started/Quorum-Examples.md
        - Creating a Network From Scratch: Getting Started/Creating-A-Network-From-Scratch.md
        - Running Quorum: Getting Started/running.md
        - Quorum API: Getting Started/api.md
    - Quorum Features: 
        - Transaction & Contract Privacy:
            - Overview: Quorum Features/Privacy/Overview.md
            - Quorum Features/Privacy/Privacy-Manager.md
            - Quorum Features/Privacy/Lifecycle-of-a-private-transaction.md
            - Tessera:
                - What is Tessera: Quorum Features/Privacy/Tessera/Tessera.md
                - Configuration:
                    - Overview: Quorum Features/Privacy/Tessera/Configuration/Configuration Overview.md
                    - Keys Config: Quorum Features/Privacy/Tessera/Configuration/Keys.md
                    - TLS Config: Quorum Features/Privacy/Tessera/Configuration/TLS.md
                    - Using CLI to override config: Quorum Features/Privacy/Tessera/Configuration/Using CLI to override config.md
                    - Sample Configuration: Quorum Features/Privacy/Tessera/Configuration/Sample Configuration.md
                - Tessera Services:
                    - Transaction Manager: Quorum Features/Privacy/Tessera/Tessera Services/Transaction Manager.md
                    - Enclave: Quorum Features/Privacy/Tessera/Tessera Services/Enclave.md
                    - Keys:
                        - Key Generation: Quorum Features/Privacy/Tessera/Tessera Services/Keys/Keys.md
                        - Setting up Hashicorp Vault: Quorum Features/Privacy/Tessera/Tessera Services/Keys/Setting up a Hashicorp Vault.md
                        - Setting up Azure Key Vault: Quorum Features/Privacy/Tessera/Tessera Services/Keys/Setting up an Azure Key Vault.md
                        - Setting up AWS Secrets Manager: Quorum Features/Privacy/Tessera/Tessera Services/Keys/Setting up an AWS Secrets Manager.md
                - Usage:
                    - Interfaces & API: Quorum Features/Privacy/Tessera/Usage/Interface & API.md
                    - Admin Usage: Quorum Features/Privacy/Tessera/Usage/Admin Usage.md
                    - Monitoring: Quorum Features/Privacy/Tessera/Usage/Monitoring.md
                    - Logging: Quorum Features/Privacy/Tessera/Usage/Logging.md
                - Migration from Constellation: Quorum Features/Privacy/Tessera/Migration from Constellation.md
            - Constellation:
                - What is Constellation: Quorum Features/Privacy/Constellation/Constellation.md
                - How it works: Quorum Features/Privacy/Constellation/How constellation works.md
                - Sample Configuration: Quorum Features/Privacy/Constellation/Sample Configuration.md
                - Running Constellation: Quorum Features/Privacy/Constellation/Installation & Running.md
        - Consensus:
            - Consensus: Quorum Features/Consensus/Consensus.md
            - Raft BFT:
                - Quorum Features/Consensus/raft/raft.md
                - Quorum Features/Consensus/raft/raft-rpc-api.md
            - Istanbul BFT:
                - Overview: Quorum Features/Consensus/ibft/ibft.md
                - Quorum Features/Consensus/ibft/istanbul-rpc-api.md
                - Quorum Features/Consensus/ibft/ibft-parameters.md     
        - Permissioning:
            - Overview: Quorum Features/Permissioning/Overview.md
            - Design: Quorum Features/Permissioning/Contract Design.md
            - Setup: Quorum Features/Permissioning/setup.md
            - APIs: Quorum Features/Permissioning/Permissioning apis.md
            - Usage: Quorum Features/Permissioning/Usage.md
        - Pluggable Architecture:
            - Overview: Quorum Features/PluggableArchitecture/Overview.md
            - Settings: Quorum Features/PluggableArchitecture/Settings.md
            - Internals: Quorum Features/PluggableArchitecture/Internals.md
            - Plugins:
                - helloworld:
                    - Interface: Quorum Features/PluggableArchitecture/Plugins/helloworld/interface.md
                    - Implementation: Quorum Features/PluggableArchitecture/Plugins/helloworld/implementation.md
            - Plugin Development: Quorum Features/PluggableArchitecture/PluginDevelopment.md
        - DNS: Quorum Features/dns.md
        - Quorum Import-Export: Quorum Features/import-export.md
    - Quorum Projects: 
        - Quorum Wizard:
            - Getting Started: Quorum Projects/Wizard/GettingStarted.md
            - Interacting with the Network: Quorum Projects/Wizard/Interacting.md
        - Cakeshop:
            - Overview: Quorum Projects/Cakeshop/Overview.md
            - Getting Started: Quorum Projects/Cakeshop/Getting started.md
            - Cakeshop FAQ: Quorum Projects/Cakeshop/Cakeshop FAQ.md
        - Remix Plugin:
            - Overview: Quorum Projects/RemixPlugin/Overview.md
            - Getting Started: Quorum Projects/RemixPlugin/GettingStarted.md
    - Security Framework:
          - Overview: Security/Framework/Overview.md
          - Quorum Network:
            - Consortium: Security/Framework/Quorum Network Security/Consortium.md
            - Quorum Node:
                - Overview: Security/Framework/Quorum Network Security/Node.md
                - Permissioning:
                    - Network Permissioning: Security/Framework/Quorum Network Security/Nodes/Permissioning/Network Permissioning.md
            - Transaction Manager: Security/Framework/Quorum Network Security/Transaction Manager.md
            - Operational Considerations: Security/Framework/Quorum Network Security/Opertional Considerations.md
          - Decentralized App:
            - Frontend: Security/Framework/Decentralized Application/Frontend Components.md
            - Smart Contracts:  Security/Framework/Decentralized Application/Smart Contracts Security.md 
    - How-To Guides:
        - Adding new nodes: How-To-Guides/adding_nodes.md
        - Adding IBFT validators: How-To-Guides/add_ibft_validator.md
        - Backup & Restore: Features/import-export.md
    - Product Roadmap: roadmap.md
    - FAQ: FAQ.md

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  language: 'en'
  logo: 'images/logo.png'
  favicon: 'images/logo-48x48.png'

extra_css:
    - 'theme/assets/stylesheets/extra.css'

markdown_extensions:
    - toc:
        permalink: true
        toc_depth: 3
    - attr_list
    - codehilite
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - markdown_include.include:
        base_path: docs
    - meta
    - smarty
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml

plugins:
    - search
